# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Mon Mar 10 16:16:18 2014
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1138, 834)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.plotLayout = QtGui.QVBoxLayout()
        self.plotLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.plotLayout.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.plotLayout, 3, 2, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.plotoptions = QtGui.QComboBox(Form)
        self.plotoptions.setObjectName(_fromUtf8("plotoptions"))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(0, QtGui.QApplication.translate("Form", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(1, QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(2, QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_9.addWidget(self.plotoptions)
        self.plotoptions2 = QtGui.QComboBox(Form)
        self.plotoptions2.setObjectName(_fromUtf8("plotoptions2"))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(0, QtGui.QApplication.translate("Form", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(1, QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(2, QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_9.addWidget(self.plotoptions2)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 3, 0, 1, 1)
        self.navbar_layout = QtGui.QVBoxLayout()
        self.navbar_layout.setSpacing(1)
        self.navbar_layout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.navbar_layout.setObjectName(_fromUtf8("navbar_layout"))
        self.gridLayout_3.addLayout(self.navbar_layout, 0, 2, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.autoscale_x = QtGui.QCheckBox(Form)
        self.autoscale_x.setText(QtGui.QApplication.translate("Form", "Autoscale X", None, QtGui.QApplication.UnicodeUTF8))
        self.autoscale_x.setChecked(True)
        self.autoscale_x.setObjectName(_fromUtf8("autoscale_x"))
        self.verticalLayout_7.addWidget(self.autoscale_x)
        self.autoscale_y = QtGui.QCheckBox(Form)
        self.autoscale_y.setText(QtGui.QApplication.translate("Form", "Autoscale Y", None, QtGui.QApplication.UnicodeUTF8))
        self.autoscale_y.setChecked(True)
        self.autoscale_y.setObjectName(_fromUtf8("autoscale_y"))
        self.verticalLayout_7.addWidget(self.autoscale_y)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.regenerate_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.regenerate_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.regenerate_button.setText(QtGui.QApplication.translate("Form", "Regenerate", None, QtGui.QApplication.UnicodeUTF8))
        self.regenerate_button.setObjectName(_fromUtf8("regenerate_button"))
        self.verticalLayout_4.addWidget(self.regenerate_button)
        self.regulate_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.regulate_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.regulate_button.setText(QtGui.QApplication.translate("Form", "Regulate", None, QtGui.QApplication.UnicodeUTF8))
        self.regulate_button.setObjectName(_fromUtf8("regulate_button"))
        self.verticalLayout_4.addWidget(self.regulate_button)
        self.stop_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.stop_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stop_button.setText(QtGui.QApplication.translate("Form", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.verticalLayout_4.addWidget(self.stop_button)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_9 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Magnet Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.magnet_voltage_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnet_voltage_value.sizePolicy().hasHeightForWidth())
        self.magnet_voltage_value.setSizePolicy(sizePolicy)
        self.magnet_voltage_value.setReadOnly(True)
        self.magnet_voltage_value.setObjectName(_fromUtf8("magnet_voltage_value"))
        self.verticalLayout_5.addWidget(self.magnet_voltage_value)
        self.label_10 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setText(QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_5.addWidget(self.label_10)
        self.magnet_current_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnet_current_value.sizePolicy().hasHeightForWidth())
        self.magnet_current_value.setSizePolicy(sizePolicy)
        self.magnet_current_value.setReadOnly(True)
        self.magnet_current_value.setObjectName(_fromUtf8("magnet_current_value"))
        self.verticalLayout_5.addWidget(self.magnet_current_value)
        self.label_11 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setText(QtGui.QApplication.translate("Form", "Cryostat Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        self.cryo_pressure_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cryo_pressure_value.sizePolicy().hasHeightForWidth())
        self.cryo_pressure_value.setSizePolicy(sizePolicy)
        self.cryo_pressure_value.setReadOnly(True)
        self.cryo_pressure_value.setObjectName(_fromUtf8("cryo_pressure_value"))
        self.verticalLayout_5.addWidget(self.cryo_pressure_value)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 6, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.temp_bridge_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_bridge_value.sizePolicy().hasHeightForWidth())
        self.temp_bridge_value.setSizePolicy(sizePolicy)
        self.temp_bridge_value.setReadOnly(True)
        self.temp_bridge_value.setObjectName(_fromUtf8("temp_bridge_value"))
        self.verticalLayout_6.addWidget(self.temp_bridge_value)
        self.label_13 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_13.setText(QtGui.QApplication.translate("Form", "Magnet Diode Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_6.addWidget(self.label_13)
        self.temp_magnet_diode_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_magnet_diode_value.sizePolicy().hasHeightForWidth())
        self.temp_magnet_diode_value.setSizePolicy(sizePolicy)
        self.temp_magnet_diode_value.setReadOnly(True)
        self.temp_magnet_diode_value.setObjectName(_fromUtf8("temp_magnet_diode_value"))
        self.verticalLayout_6.addWidget(self.temp_magnet_diode_value)
        self.label_5 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Floating Diode Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.temp_floating_diode_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_floating_diode_value.sizePolicy().hasHeightForWidth())
        self.temp_floating_diode_value.setSizePolicy(sizePolicy)
        self.temp_floating_diode_value.setReadOnly(True)
        self.temp_floating_diode_value.setObjectName(_fromUtf8("temp_floating_diode_value"))
        self.verticalLayout_6.addWidget(self.temp_floating_diode_value)
        self.label_4 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_4.setText(QtGui.QApplication.translate("Form", "50K Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.temp_50k_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_50k_value.sizePolicy().hasHeightForWidth())
        self.temp_50k_value.setSizePolicy(sizePolicy)
        self.temp_50k_value.setReadOnly(True)
        self.temp_50k_value.setObjectName(_fromUtf8("temp_50k_value"))
        self.verticalLayout_6.addWidget(self.temp_50k_value)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_6.setText(QtGui.QApplication.translate("Form", "Pid Output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.pid_output_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pid_output_value.sizePolicy().hasHeightForWidth())
        self.pid_output_value.setSizePolicy(sizePolicy)
        self.pid_output_value.setReadOnly(True)
        self.pid_output_value.setObjectName(_fromUtf8("pid_output_value"))
        self.verticalLayout_2.addWidget(self.pid_output_value)
        self.label_7 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_7.setText(QtGui.QApplication.translate("Form", "Pid Setpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.pid_setpoint_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pid_setpoint_value.sizePolicy().hasHeightForWidth())
        self.pid_setpoint_value.setSizePolicy(sizePolicy)
        self.pid_setpoint_value.setReadOnly(True)
        self.pid_setpoint_value.setObjectName(_fromUtf8("pid_setpoint_value"))
        self.verticalLayout_2.addWidget(self.pid_setpoint_value)
        self.label_12 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_12.setText(QtGui.QApplication.translate("Form", "Pid Manual Out", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.pid_manual_output_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pid_manual_output_value.sizePolicy().hasHeightForWidth())
        self.pid_manual_output_value.setSizePolicy(sizePolicy)
        self.pid_manual_output_value.setReadOnly(True)
        self.pid_manual_output_value.setObjectName(_fromUtf8("pid_manual_output_value"))
        self.verticalLayout_2.addWidget(self.pid_manual_output_value)
        self.label_8 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_8.setText(QtGui.QApplication.translate("Form", "Pid Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.pid_mode_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pid_mode_value.sizePolicy().hasHeightForWidth())
        self.pid_mode_value.setSizePolicy(sizePolicy)
        self.pid_mode_value.setReadOnly(True)
        self.pid_mode_value.setObjectName(_fromUtf8("pid_mode_value"))
        self.verticalLayout_2.addWidget(self.pid_mode_value)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 4, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(5, 25, 5, 25)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_17 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_17.setText(QtGui.QApplication.translate("Form", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout.addWidget(self.label_17)
        self.state_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state_value.sizePolicy().hasHeightForWidth())
        self.state_value.setSizePolicy(sizePolicy)
        self.state_value.setReadOnly(True)
        self.state_value.setObjectName(_fromUtf8("state_value"))
        self.verticalLayout.addWidget(self.state_value)
        self.label_18 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setText(QtGui.QApplication.translate("Form", "Flag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout.addWidget(self.label_18)
        self.flag_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flag_value.sizePolicy().hasHeightForWidth())
        self.flag_value.setSizePolicy(sizePolicy)
        self.flag_value.setReadOnly(True)
        self.flag_value.setObjectName(_fromUtf8("flag_value"))
        self.verticalLayout.addWidget(self.flag_value)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 5, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_2 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Regulate Setpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_8.addWidget(self.label_2)
        self.setpoint_value = QtGui.QDoubleSpinBox(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setpoint_value.setFont(font)
        self.setpoint_value.setDecimals(3)
        self.setpoint_value.setMaximum(4.0)
        self.setpoint_value.setSingleStep(0.001)
        self.setpoint_value.setProperty("value", 1.45)
        self.setpoint_value.setObjectName(_fromUtf8("setpoint_value"))
        self.verticalLayout_8.addWidget(self.setpoint_value)
        self.label_14 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_14.setText(QtGui.QApplication.translate("Form", "Peak Current", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_8.addWidget(self.label_14)
        self.peak_current_value = QtGui.QDoubleSpinBox(self.tabWidgetPage1)
        self.peak_current_value.setDecimals(2)
        self.peak_current_value.setMaximum(9.4)
        self.peak_current_value.setSingleStep(0.01)
        self.peak_current_value.setProperty("value", 0.8)
        self.peak_current_value.setObjectName(_fromUtf8("peak_current_value"))
        self.verticalLayout_8.addWidget(self.peak_current_value)
        self.label_15 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_15.setText(QtGui.QApplication.translate("Form", "Ramp Rate Up", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_8.addWidget(self.label_15)
        self.ramp_rate_up_value = QtGui.QDoubleSpinBox(self.tabWidgetPage1)
        self.ramp_rate_up_value.setDecimals(3)
        self.ramp_rate_up_value.setMinimum(0.0)
        self.ramp_rate_up_value.setMaximum(0.1)
        self.ramp_rate_up_value.setSingleStep(0.001)
        self.ramp_rate_up_value.setProperty("value", 0.05)
        self.ramp_rate_up_value.setObjectName(_fromUtf8("ramp_rate_up_value"))
        self.verticalLayout_8.addWidget(self.ramp_rate_up_value)
        self.label_16 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_16.setText(QtGui.QApplication.translate("Form", "Ramp Rate Down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_8.addWidget(self.label_16)
        self.ramp_rate_down_value = QtGui.QDoubleSpinBox(self.tabWidgetPage1)
        self.ramp_rate_down_value.setDecimals(3)
        self.ramp_rate_down_value.setMinimum(0.0)
        self.ramp_rate_down_value.setMaximum(0.1)
        self.ramp_rate_down_value.setSingleStep(0.001)
        self.ramp_rate_down_value.setProperty("value", 0.025)
        self.ramp_rate_down_value.setObjectName(_fromUtf8("ramp_rate_down_value"))
        self.verticalLayout_8.addWidget(self.ramp_rate_down_value)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.lineEdit = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 113, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit_2.setGeometry(QtCore.QRect(430, 70, 113, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 70, 113, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("Form", "Main Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QtGui.QApplication.translate("Form", "Other tabs go here", None, QtGui.QApplication.UnicodeUTF8))

