# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Wed Feb 12 16:37:23 2014
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(885, 566)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setText(QtGui.QApplication.translate("Form", "For future commands", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Regenerate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "Regulate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setText(QtGui.QApplication.translate("Form", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_9 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Magnet Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.magnet_voltage_value = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnet_voltage_value.sizePolicy().hasHeightForWidth())
        self.magnet_voltage_value.setSizePolicy(sizePolicy)
        self.magnet_voltage_value.setReadOnly(True)
        self.magnet_voltage_value.setObjectName(_fromUtf8("magnet_voltage_value"))
        self.verticalLayout_5.addWidget(self.magnet_voltage_value)
        self.label_10 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setText(QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_5.addWidget(self.label_10)
        self.magnet_current_value = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnet_current_value.sizePolicy().hasHeightForWidth())
        self.magnet_current_value.setSizePolicy(sizePolicy)
        self.magnet_current_value.setReadOnly(True)
        self.magnet_current_value.setObjectName(_fromUtf8("magnet_current_value"))
        self.verticalLayout_5.addWidget(self.magnet_current_value)
        self.label_11 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setText(QtGui.QApplication.translate("Form", "Cryostat Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        self.cryo_pressure_value = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cryo_pressure_value.sizePolicy().hasHeightForWidth())
        self.cryo_pressure_value.setSizePolicy(sizePolicy)
        self.cryo_pressure_value.setReadOnly(True)
        self.cryo_pressure_value.setObjectName(_fromUtf8("cryo_pressure_value"))
        self.verticalLayout_5.addWidget(self.cryo_pressure_value)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.temp_bridge_value = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_bridge_value.sizePolicy().hasHeightForWidth())
        self.temp_bridge_value.setSizePolicy(sizePolicy)
        self.temp_bridge_value.setReadOnly(True)
        self.temp_bridge_value.setObjectName(_fromUtf8("temp_bridge_value"))
        self.verticalLayout_6.addWidget(self.temp_bridge_value)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setText(QtGui.QApplication.translate("Form", "3K Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.temp_3k_value = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_3k_value.sizePolicy().hasHeightForWidth())
        self.temp_3k_value.setSizePolicy(sizePolicy)
        self.temp_3k_value.setReadOnly(True)
        self.temp_3k_value.setObjectName(_fromUtf8("temp_3k_value"))
        self.verticalLayout_6.addWidget(self.temp_3k_value)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setText(QtGui.QApplication.translate("Form", "50K Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.temp_50k_value = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_50k_value.sizePolicy().hasHeightForWidth())
        self.temp_50k_value.setSizePolicy(sizePolicy)
        self.temp_50k_value.setReadOnly(True)
        self.temp_50k_value.setObjectName(_fromUtf8("temp_50k_value"))
        self.verticalLayout_6.addWidget(self.temp_50k_value)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.plotoptions = QtGui.QComboBox(Form)
        self.plotoptions.setObjectName(_fromUtf8("plotoptions"))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(0, QtGui.QApplication.translate("Form", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(1, QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(2, QtGui.QApplication.translate("Form", "Bridge Setpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(3, QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_3.addWidget(self.plotoptions, 2, 0, 1, 1)
        self.plotLayout = QtGui.QVBoxLayout()
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.plotLayout.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.plotLayout, 2, 1, 1, 1)
        self.plotLayout_2 = QtGui.QVBoxLayout()
        self.plotLayout_2.setObjectName(_fromUtf8("plotLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.plotLayout_2.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.plotLayout_2.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.plotLayout_2, 3, 1, 1, 1)
        self.plotoptions2 = QtGui.QComboBox(Form)
        self.plotoptions2.setObjectName(_fromUtf8("plotoptions2"))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(0, QtGui.QApplication.translate("Form", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(1, QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(2, QtGui.QApplication.translate("Form", "Bridge Setpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(3, QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_3.addWidget(self.plotoptions2, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Number One", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Page", None, QtGui.QApplication.UnicodeUTF8))

