# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Mon Mar  3 10:58:39 2014
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1138, 834)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.plotLayout = QtGui.QVBoxLayout()
        self.plotLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.plotLayout.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.plotLayout, 2, 1, 1, 1)
        self.plotLayout_2 = QtGui.QVBoxLayout()
        self.plotLayout_2.setObjectName(_fromUtf8("plotLayout_2"))
        self.gridLayout_3.addLayout(self.plotLayout_2, 3, 1, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.plotoptions = QtGui.QComboBox(Form)
        self.plotoptions.setObjectName(_fromUtf8("plotoptions"))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(0, QtGui.QApplication.translate("Form", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(1, QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions.addItem(_fromUtf8(""))
        self.plotoptions.setItemText(2, QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_9.addWidget(self.plotoptions)
        self.plotoptions2 = QtGui.QComboBox(Form)
        self.plotoptions2.setObjectName(_fromUtf8("plotoptions2"))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(0, QtGui.QApplication.translate("Form", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(1, QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.plotoptions2.addItem(_fromUtf8(""))
        self.plotoptions2.setItemText(2, QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_9.addWidget(self.plotoptions2)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 2, 0, 1, 1)
        self.label = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText(QtGui.QApplication.translate("Form", "Navbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.navbar_layout = QtGui.QVBoxLayout()
        self.navbar_layout.setSpacing(1)
        self.navbar_layout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.navbar_layout.setObjectName(_fromUtf8("navbar_layout"))
        self.gridLayout_3.addLayout(self.navbar_layout, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(9)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.regenerate_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.regenerate_button.setText(QtGui.QApplication.translate("Form", "Regenerate", None, QtGui.QApplication.UnicodeUTF8))
        self.regenerate_button.setObjectName(_fromUtf8("regenerate_button"))
        self.verticalLayout_4.addWidget(self.regenerate_button)
        self.regulate_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.regulate_button.setText(QtGui.QApplication.translate("Form", "Regulate", None, QtGui.QApplication.UnicodeUTF8))
        self.regulate_button.setObjectName(_fromUtf8("regulate_button"))
        self.verticalLayout_4.addWidget(self.regulate_button)
        self.stop_button = QtGui.QPushButton(self.tabWidgetPage1)
        self.stop_button.setText(QtGui.QApplication.translate("Form", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.verticalLayout_4.addWidget(self.stop_button)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_9 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Magnet Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_5.addWidget(self.label_9)
        self.magnet_voltage_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnet_voltage_value.sizePolicy().hasHeightForWidth())
        self.magnet_voltage_value.setSizePolicy(sizePolicy)
        self.magnet_voltage_value.setReadOnly(True)
        self.magnet_voltage_value.setObjectName(_fromUtf8("magnet_voltage_value"))
        self.verticalLayout_5.addWidget(self.magnet_voltage_value)
        self.label_10 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setText(QtGui.QApplication.translate("Form", "Magnet Current", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_5.addWidget(self.label_10)
        self.magnet_current_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnet_current_value.sizePolicy().hasHeightForWidth())
        self.magnet_current_value.setSizePolicy(sizePolicy)
        self.magnet_current_value.setReadOnly(True)
        self.magnet_current_value.setObjectName(_fromUtf8("magnet_current_value"))
        self.verticalLayout_5.addWidget(self.magnet_current_value)
        self.label_11 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setText(QtGui.QApplication.translate("Form", "Cryostat Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        self.cryo_pressure_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cryo_pressure_value.sizePolicy().hasHeightForWidth())
        self.cryo_pressure_value.setSizePolicy(sizePolicy)
        self.cryo_pressure_value.setReadOnly(True)
        self.cryo_pressure_value.setObjectName(_fromUtf8("cryo_pressure_value"))
        self.verticalLayout_5.addWidget(self.cryo_pressure_value)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 5, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Bridge Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.temp_bridge_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_bridge_value.sizePolicy().hasHeightForWidth())
        self.temp_bridge_value.setSizePolicy(sizePolicy)
        self.temp_bridge_value.setReadOnly(True)
        self.temp_bridge_value.setObjectName(_fromUtf8("temp_bridge_value"))
        self.verticalLayout_6.addWidget(self.temp_bridge_value)
        self.label_5 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_5.setText(QtGui.QApplication.translate("Form", "3K Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.temp_3k_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_3k_value.sizePolicy().hasHeightForWidth())
        self.temp_3k_value.setSizePolicy(sizePolicy)
        self.temp_3k_value.setReadOnly(True)
        self.temp_3k_value.setObjectName(_fromUtf8("temp_3k_value"))
        self.verticalLayout_6.addWidget(self.temp_3k_value)
        self.label_4 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_4.setText(QtGui.QApplication.translate("Form", "50K Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.temp_50k_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_50k_value.sizePolicy().hasHeightForWidth())
        self.temp_50k_value.setSizePolicy(sizePolicy)
        self.temp_50k_value.setReadOnly(True)
        self.temp_50k_value.setObjectName(_fromUtf8("temp_50k_value"))
        self.verticalLayout_6.addWidget(self.temp_50k_value)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(-1, 35, -1, 35)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_2 = QtGui.QLabel(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Set Bridge Setpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_8.addWidget(self.label_2)
        self.bridge_setpoint_command_value = QtGui.QDoubleSpinBox(self.tabWidgetPage1)
        self.bridge_setpoint_command_value.setMaximum(0.5)
        self.bridge_setpoint_command_value.setSingleStep(0.1)
        self.bridge_setpoint_command_value.setObjectName(_fromUtf8("bridge_setpoint_command_value"))
        self.verticalLayout_8.addWidget(self.bridge_setpoint_command_value)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 35, 0, 35)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_6.setText(QtGui.QApplication.translate("Form", "Pid Output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.pid_output_value = QtGui.QLineEdit(self.tabWidgetPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pid_output_value.sizePolicy().hasHeightForWidth())
        self.pid_output_value.setSizePolicy(sizePolicy)
        self.pid_output_value.setReadOnly(True)
        self.pid_output_value.setObjectName(_fromUtf8("pid_output_value"))
        self.verticalLayout_2.addWidget(self.pid_output_value)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.lineEdit = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 113, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit_2.setGeometry(QtCore.QRect(430, 70, 113, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tabWidgetPage2)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 70, 113, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), QtGui.QApplication.translate("Form", "Main Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), QtGui.QApplication.translate("Form", "Other tabs go here", None, QtGui.QApplication.UnicodeUTF8))

